[workspace]
members = [
    "clacks_crypto",
    "clacks_demos",
    "clacks_mtproto",
    "clacks_tl_codegen",
    "clacks_transport",
    "keyring-rs",
    "rust-security-framework/security-framework-sys",
    "rust-security-framework/security-framework",
]
