max_width = 120
ideal_width = 90
fn_call_width = 80

match_block_trailing_comma = true
reorder_imported_names = true
reorder_imports = true
use_try_shorthand = true
where_trailing_comma = true
wrap_comments = true

fn_args_density = "compressed"
