[package]
name = "clacks_tl_codegen"
version = "0.0.2"
authors = ["Aaron Gallagher <_@habnab.it>", "Connie Hilarides <connorcpu@live.com>"]
license = "MIT/Apache-2.0"
description = "codegen for clacks"

[dependencies]
pom = "1"
syn = "0.13"
quote = "0.5"
