[package]
name = "security-framework"
version = "0.1.8"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Security Framework bindings"
repository = "https://github.com/sfackler/rust-security-framework"
documentation = "https://sfackler.github.io/rust-security-framework/doc/v0.1.8/security_framework"
readme = "../README.md"
keywords = ["OSX", "iOS", "TLS", "SSL", "crypto"]
exclude = ["test/*"]

[dependencies]
security-framework-sys = { version = "0.1.8", path = "../security-framework-sys" }
core-foundation = "0.2.1"
core-foundation-sys = "0.2.1"
libc = "0.2"

[dev-dependencies]
tempdir = "0.3"
hex = "0.2"

[features]
OSX_10_8 = ["security-framework-sys/OSX_10_8"]
OSX_10_9 = ["OSX_10_8", "security-framework-sys/OSX_10_9"]
OSX_10_10 = ["OSX_10_9", "security-framework-sys/OSX_10_10"]
OSX_10_11 = ["OSX_10_10", "security-framework-sys/OSX_10_11"]

nightly = []
default_keychain_tests = []
