[package]
description = "Publish-Subscribe extension for jsonrpc."
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-pubsub"
version = "8.0.1"
authors = ["tomusdrw <tomasz@parity.io>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://paritytech.github.io/jsonrpc/jsonrpc_pubsub/index.html"

[dependencies]
log = "0.4"
parking_lot = "0.6"
jsonrpc-core = { version = "8.0", path = "../core" }

[dev-dependencies]
jsonrpc-tcp-server = { version = "8.0", path = "../tcp" }

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
