[package]
name = "kabuki"
version = "0.0.2"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Name reservation"
license = "MIT"

[dependencies]
futures = "0.1"
scoped-tls = "0.1.0"
tokio-service = "0.1"
